const router = require('express').Router();
const verify = require('./verifytoken')
router.get('/',verify, (req,res)=>{
  res.json({
    categories: {
    'Minerals & Meteorites' : [['Decorative Minerals', 'Meteorites' ,  'Minerals', 'Premium Minerals'],['Number of Items' , 'Main Mineral/ Name Meteorite' , 'Mineral Form/ Type Meteorites' ,'Supplements' ,'Dimensions' , 'Weight' , 'Origin (Region/City)' , 'Origin (country)' , 'Descrption'],['text input',  'drop down menu' ,'drop down menu' ,'text input' , 'drop down menu' , 'drop down menu' , 'text input', 'drop down menu' , 'text box']],
    'Fossils' : [[],['Specimen', 'Object' , 'Scientific name' ,'Origin' ,'Geological Period' , 'Condition' ,'Treatment' , 'Dimensions' , 'Weight' , 'Description' ],[ 'drop down menu' , 'drop down menu' , 'drop down menu' ,'drop down menu' , 'drop down menu', 'drop down menu' , 'drop down menu' , 'drop down menu', 'drop down menu',  'text box']],
    'Bullion' : [[],['Weight' , 'Material' , 'Fineness' , 'Seal/Certification', 'Shape' , 'Dealer/Refiner', 'Description' ],['drop down menu', 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' ,'text box']],
     'Diamond and Gemstones' : {'Diamonds' : [['Color Treated Diamonds', 'Mixed Diamonds', 'Diamonds', 'Natural Fancy Color Diamonds'],['Number of Stones' ,'Stone' , 'Total Carat Weight' , 'Shape/Cut' , 'White Color' , 'Natural Fancy Color' , 'Clarity' , 'Treatment', 'Certification', 'Sealed', 'Laser Engraved', 'Description'],['text input' , 'drop down menu' , 'text input' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'radio button yes/no',  'radio button yes/no', 'text box']]},
    'Gemstones' : [['Exclusive gemstones', 'Gemstones Certified By Gemologist', 'Parcel Of Gemstones', 'Gemstones', 'Spiritual & Healing gemstones'],['No. of Stones' , 'Stone', 'Carat Weight of Individual Stones' , 'Total Carat Weight', 'Origin as given on Certificate', 'Cut & Shape', 'Certification', 'Colour', 'Treatment', 'Transparency/ Clarity' , 'Sealed', 'Description'],[ 'text input' , 'drop down menu' , 'text input' , 'text input', 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'radio button yes/no' , 'text box']]},

    'Jewelry & Watches': {'Jewelry':[['Antique & Vintage Amber Jewellery','Antique & Vintage Men’s Jewellery','Antique & Vintage Silver Jewellery','Antique Jewellery','Art Nouveau & Art Deco Jewellery','Brand Jewellery', 'Enhanced Diamond Jewellery', 'Exclusive & Certified Jewellery', 'Exclusive Antique Jewellery', 'Exclusive Jewellery','Exclusive Jewelry (No Reserve)', 'Fine Jewellery', 'Jewellery Set with Magnificent Jewels', 'Men’s Jewellery', 'Premium Jewellery', 'Professional Designers', 'Vintage Jewelry'],['Type' , 'Gender', 'Material,Material Fineness', 'Brand, Size', 'Total Weight' , 'Condition', 'Main Stone', 'Main Stone Treatment', 'Carat Weight main stone', 'Surrounding Stones', 'Total Carat weight surrounding stones', 'Diamond Clarity Grade', 'Diamond Colour Grade', 'Description'],[ 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'text input' ,  'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'text input' , 'drop down menu' , 'text input' , 'drop down menu' , 'drop down menu' , 'text box']],
    'Watches': [['Briefing watches', 'Cartier Watches', 'Eberhard Watches', 'Exclusive Marriage Watches', 'Exclusive Men’s watches', 'Exclusive Pocket watches', 'Exclusive Watches', 'IWC Watches', 'Jaeger-LeCoultre Watches', 'Ladies watches','Longines Watches', 'Omega Watches', 'Pocket Watches', 'Premium Watches', 'Rolex Watches', 'Rolex Accessories', 'Seiko Watches', 'Solid Gold & Platinum Watches', 'Tag Heuer Watches', 'Tudor Watches', 'Unused Exclusive Watches', 'Unused premium Watches', 'Vintage Watches', 'Watches (No Reserve)','Zenit Watches' ],['Brand, Model', 'Reference Number', 'Gender', 'Period', 'Movement', 'Case Material', 'Material Fineness', 'Extras', 'Type', 'Shipped Insured', 'Condition', 'Description'],['drop down menu' , 'text input' , 'text input' , 'drop down menu' ,'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu' , 'drop down menu', 'drop down menu' , 'radio button yes/no' , 'drop down menu', 'text box']] }



  })
})

module.exports = router;
